Repository MicrosoftDocs/xamarin-docs.zh-cn, pull requests merged in 2018-11, with the labels that each got.

#26 Update part2.md
  docs/graphics-games/monogame/3d/part2.md
Labels: In Progress, Linguistic Suggestion

#27 Updated translation to index.md and preface.md
  docs/xamarin-forms/enterprise-application-patterns/index.md
  docs/xamarin-forms/enterprise-application-patterns/preface.md
Labels: Accepted, Linguistic Suggestion, Rejected

#28 update translation to introduction.md
  docs/xamarin-forms/enterprise-application-patterns/introduction.md
Labels: Accepted, Linguistic Suggestion
